### PR TITLE
We should skip the non-existing text unit and continue importing tran…

### PR DESCRIPTION
**Pull request by jeeyi**
…slations

@aurambaj We ran into issues while importing exported tm xliffs because some of the xliffs had translation for non-existing translation units. I think skipping them is better than throwing run-time exception and aborting the whole import process. Let me know what you think.

Do you know why we have some translations in the exported localized tm xliffs for the text unit that is not in the source tm xliff?

### CODE REVIEW

**Comment by aurambaj** [comment]
@jeeyi With the current implementation, I think the hard error make sense. We don't remove text units as far as I know so there must be a bug somewhere else. 

Did you check if the entry was in the DB?

**Comment by jeeyi** [comment]
@aurambaj The text unit differences come from plurals. In English tm xliff, I have text unit `*_one` and `*_other`. In localized tm xliff for `ar-SA`, I have more text units according to the plural rules. `tm-import` gets terminated when it tries to import translation for `*_zero` because it is not in the English tm xliff and considered as adding a translation to a non-existing text unit.

**Comment by aurambaj** [comment]
oh when importing plural strings for the source it should actually create all forms, that's the issue. Your fix can be a temporary solution, though

Why do still use that feature btw, what's the use case?

**Comment by aurambaj** [comment]
@jeeyi btw, if you re-generate the source file they should have all the plural form, right?

**Comment by jeeyi** [comment]
@aurambaj You mean, if I push the source file? Let me test it. I think it should work.

**Pull request merged**
