### PR TITLE
New android filter and support variable plural form

### PR DESCRIPTION
**Pull request by aurambaj**
Search for strings with plural:
Search for string with plural

1 plural string in French, 2 forms:
string with 2 forms

Same string in Russian, 4 forms:
screen shot 2017-10-18 at 5 53 16 pm

Checking the "one" form in all languages:
screen shot 2017-10-18 at 5 53 32 pm

### CODE REVIEW

**Comment by aurambaj** [comment]
Search for string with plural

string with 2 forms

**Comment by aurambaj** [comment]
missing pluralforms for es-419 since that locale was added recently

**Comment by jeeyi** [comment]
I am adding one more locale - bn-IN.  Could we also add the plural forms for that locale? Thanks!

**Comment by aurambaj** [comment]
@jeeyi I've added the locale in "pmaster" branch because keep adding feature there too. Closing that PR. Instead I'd like to merge "pmaster" into "master". If you have time to check that branch instead then I could merge

**Pull request closed without merging**
