### PR TITLE
Fix incorrect and confusing help message in the cli

### PR DESCRIPTION
**Pull request by ehoogerbeets**
Only a string fix. No code/logic changes.

### CODE REVIEW

**Comment by aurambaj** [comment]
I thought both notation are working. All our doc use the old notation at least. Did you have an issue with it?

**Comment by ehoogerbeets** [comment]
Yeah, spaces don't work there... Is the proper fix to change the code to support both?

**Comment by aurambaj** [comment]
Can you copy the command you're running because if I copy/paste the list from the doc it works for me: `mojito repo-create -n test -l "fr-FR" "(fr-CA)->fr-FR" "en-GB" "(en-CA)->en-GB" "en-AU"`

**Comment by ehoogerbeets** [comment]
This works:

`mojito repo-create -n test -l "fr-FR,(fr-CA)->fr-FR,en-GB,(en-CA)->en-GB,en-AU"`

This doesn't:

`mojito repo-create -n test -l "fr-FR (fr-CA)->fr-FR en-GB (en-CA)->en-GB en-AU"`

**Comment by aurambaj** [comment]
oh yeah, it is a var arg, so either this `mojito repo-create -n test -l "fr-FR" "(fr-CA)->fr-FR" "en-GB" "(en-CA)->en-GB" "en-AU"` or `mojito repo-create -n test -l "fr-FR,(fr-CA)->fr-FR,en-GB,(en-CA)->en-GB,en-AU"`

The one that doesn't work it not the one from the documentation though.

**Comment by aurambaj** [comment]
closing this since the documentation is "ok".

**Pull request closed without merging**
